#!/bin/bash

# Build and run the xframes docker container 
sudo docker stop xframes
sudo docker rm xframes
sudo docker build -t xframes .
sudo docker run -d -p 8888:8888 -e "USE_HTTP=1" --name xframes xframes
