#!/bin/bash

# This docker is contains an HDFS file system, accessed through hdfs server interface

if [ -z ${XFRAMES_HOME+x} ]
then
  echo "XFRAMES_HOME is not set"
  exit 1
fi

# runs hdfs docker on localhost:8020
# Returned urls have the hostname xpatterns-hadoop, so map them to 127.0.0.1 in /etc/hosts

CACHE=${XFRAMES_HOME}/../cache

docker run -dt -p 8020:8020 -p 50070:50070 -p 50075:50075 \
    -v "$CACHE":/var/lib/hadoop-hdfs/cache \
    -v "${XFRAMES_HOME}/dockdir":/opt/xframes \
    --hostname xpatterns-hadoop xpatterns/hadoop:1.3.3
