#!/usr/bin/env bash
# Set up the environment for command-line and notebook based execution.
# This file should be run as follows:
# source setup

export LIB=`pwd`
export PYTHONPATH=$LIB
export SPARK_HOME=/usr/local/spark
export SPARK_CONF_DIR=/notebooks/conf

# Add the PySpark classes to the Python path:
export PYTHONPATH="$SPARK_HOME/python/:$PYTHONPATH"
export PYTHONPATH="$SPARK_HOME/python/lib/py4j-0.8.2.1-src.zip:$PYTHONPATH"
